#ifndef KEYBINDS_H
#define KEYBINDS_H

#define KEY_RIGHT SDL_SCANCODE_D
#define KEY_LEFT SDL_SCANCODE_A
#define KEY_UP SDL_SCANCODE_W
#define KEY_DOWN SDL_SCANCODE_S
#define KEY_JUMP SDL_SCANCODE_SPACE
#define KEY_ENTER SDL_SCANCODE_RETURN

#endif