#ifndef KEYBINDS_H
#define KEYBINDS_H

//movement + menus
#define KEY_RIGHT SDL_SCANCODE_D
#define KEY_LEFT SDL_SCANCODE_A
#define KEY_UP SDL_SCANCODE_W
#define KEY_DOWN SDL_SCANCODE_S
#define KEY_JUMP SDL_SCANCODE_SPACE
#define KEY_ENTER SDL_SCANCODE_RETURN

//combat
#define KEY_PAUSE SDL_SCANCODE_SPACE
#define KEY_ATTACK SDL_SCANCODE_U
#define KEY_ITEMS SDL_SCANCODE_I

#endif